In [1]:
import pandas as pd

#save filename to a variable called filename
filename=r'C:/Users/xsnow/Desktop/School/Semester 7/Comp 598/comp598-2021/hw1/submission_template/data/IRAhandle_tweets_1.csv'

tweets=pd.read_csv(filename) #read the file into the code

In [9]:
tweets=tweets.head(10000) #look at the first 10000 tweets
tweets

,external_author_id,author,content,region,language,publish_date,harvested_date,following,followers,updates,...,account_type,retweet,account_category,new_june_2018,alt_external_id,tweet_id,article_url,tco1_step1,tco2_step1,tco3_step1
0,906000000000000000,10_GOP,"""We have a sitting Democrat US Senator on tria...",Unknown,English,10/1/2017 19:58,10/1/2017 19:59,1052,9636,253,...,Right,0,RightTroll,0,905874659358453760,914580356430536707,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/914580356430...,NaN,NaN
1,906000000000000000,10_GOP,Marshawn Lynch arrives to game in anti-Trump s...,Unknown,English,10/1/2017 22:43,10/1/2017 22:43,1054,9637,254,...,Right,0,RightTroll,0,905874659358453760,914621840496189440,http://twitter.com/905874659358453760/statuses...,https://twitter.com/damienwoody/status/9145685...,NaN,NaN
2,906000000000000000,10_GOP,Daughter of fallen Navy Sailor delivers powerf...,Unknown,English,10/1/2017 22:50,10/1/2017 22:51,1054,9637,255,...,Right,1,RightTroll,0,905874659358453760,914623490375979008,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/913231923715...,NaN,NaN
3,906000000000000000,10_GOP,JUST IN: President Trump dedicates Presidents ...,Unknown,English,10/1/2017 23:52,10/1/2017 23:52,1062,9642,256,...,Right,0,RightTroll,0,905874659358453760,914639143690555392,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/914639143690...,NaN,NaN
4,906000000000000000,10_GOP,"19,000 RESPECTING our National Anthem! #StandF...",Unknown,English,10/1/2017 2:13,10/1/2017 2:13,1050,9645,246,...,Right,1,RightTroll,0,905874659358453760,914312219952861184,http://twitter.com/905874659358453760/statuses...,https://twitter.com/realDonaldTrump/status/914...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,3312143142,4MYSQUAD,'@SARAH2TURNNT I love U',United States,LANGUAGE UNDEFINED,9/9/2015 1:13,9/9/2015 1:19,1311,618,2091,...,Left,0,LeftTroll,0,3312143142,641419031673618432,http://twitter.com/4mysquad/statuses/641419031...,NaN,NaN,NaN
9996,3312143142,4MYSQUAD,Rebecca Martin: Public Comment Against More #C...,United States,English,9/9/2015 1:18,9/9/2015 1:18,1311,618,2091,...,Left,0,LeftTroll,0,3312143142,641420337356210176,http://twitter.com/4mysquad/statuses/641420337...,https://www.youtube.com/watch?v=ffCiHzqMJIA,NaN,NaN
9997,3312143142,4MYSQUAD,'@ThisIsRobThomas If You believe - you act',United States,English,9/9/2015 1:29,9/9/2015 1:29,1311,620,2096,...,Left,0,LeftTroll,0,3312143142,641423168989630465,http://twitter.com/4mysquad/statuses/641423168...,NaN,NaN,NaN
9998,3312143142,4MYSQUAD,'@tyriquex when my girl refused to stop painti...,United States,English,9/9/2015 1:31,9/9/2015 1:31,1311,620,2097,...,Left,0,LeftTroll,0,3312143142,641423659505090560,http://twitter.com/4mysquad/statuses/641423659...,NaN,NaN,NaN
9999,3312143142,4MYSQUAD,'@deray New York State Of Mind',United States,English,9/9/2015 1:31,9/9/2015 1:31,1311,620,2098,...,Left,0,LeftTroll,0,3312143142,641423736013385728,http://twitter.com/4mysquad/statuses/641423736...,NaN,NaN,NaN

In [12]:
tweets_df=pd.DataFrame(tweets)

In [30]:
tweets_df = tweets_df[tweets_df.language == 'English']
tweets_df.shape

(5345, 21)

In [31]:
tweets_df

,external_author_id,author,content,region,language,publish_date,harvested_date,following,followers,updates,...,account_type,retweet,account_category,new_june_2018,alt_external_id,tweet_id,article_url,tco1_step1,tco2_step1,tco3_step1
0,906000000000000000,10_GOP,"""We have a sitting Democrat US Senator on tria...",Unknown,English,10/1/2017 19:58,10/1/2017 19:59,1052,9636,253,...,Right,0,RightTroll,0,905874659358453760,914580356430536707,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/914580356430...,NaN,NaN
1,906000000000000000,10_GOP,Marshawn Lynch arrives to game in anti-Trump s...,Unknown,English,10/1/2017 22:43,10/1/2017 22:43,1054,9637,254,...,Right,0,RightTroll,0,905874659358453760,914621840496189440,http://twitter.com/905874659358453760/statuses...,https://twitter.com/damienwoody/status/9145685...,NaN,NaN
2,906000000000000000,10_GOP,Daughter of fallen Navy Sailor delivers powerf...,Unknown,English,10/1/2017 22:50,10/1/2017 22:51,1054,9637,255,...,Right,1,RightTroll,0,905874659358453760,914623490375979008,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/913231923715...,NaN,NaN
3,906000000000000000,10_GOP,JUST IN: President Trump dedicates Presidents ...,Unknown,English,10/1/2017 23:52,10/1/2017 23:52,1062,9642,256,...,Right,0,RightTroll,0,905874659358453760,914639143690555392,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/914639143690...,NaN,NaN
4,906000000000000000,10_GOP,"19,000 RESPECTING our National Anthem! #StandF...",Unknown,English,10/1/2017 2:13,10/1/2017 2:13,1050,9645,246,...,Right,1,RightTroll,0,905874659358453760,914312219952861184,http://twitter.com/905874659358453760/statuses...,https://twitter.com/realDonaldTrump/status/914...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,3312143142,4MYSQUAD,'@EdgeofSports @deray does she make that tenni...,United States,English,9/9/2015 1:09,9/9/2015 1:09,1311,618,2083,...,Left,0,LeftTroll,0,3312143142,641418070649540608,http://twitter.com/4mysquad/statuses/641418070...,NaN,NaN,NaN
9996,3312143142,4MYSQUAD,Rebecca Martin: Public Comment Against More #C...,United States,English,9/9/2015 1:18,9/9/2015 1:18,1311,618,2091,...,Left,0,LeftTroll,0,3312143142,641420337356210176,http://twitter.com/4mysquad/statuses/641420337...,https://www.youtube.com/watch?v=ffCiHzqMJIA,NaN,NaN
9997,3312143142,4MYSQUAD,'@ThisIsRobThomas If You believe - you act',United States,English,9/9/2015 1:29,9/9/2015 1:29,1311,620,2096,...,Left,0,LeftTroll,0,3312143142,641423168989630465,http://twitter.com/4mysquad/statuses/641423168...,NaN,NaN,NaN
9998,3312143142,4MYSQUAD,'@tyriquex when my girl refused to stop painti...,United States,English,9/9/2015 1:31,9/9/2015 1:31,1311,620,2097,...,Left,0,LeftTroll,0,3312143142,641423659505090560,http://twitter.com/4mysquad/statuses/641423659...,NaN,NaN,NaN
9999,3312143142,4MYSQUAD,'@deray New York State Of Mind',United States,English,9/9/2015 1:31,9/9/2015 1:31,1311,620,2098,...,Left,0,LeftTroll,0,3312143142,641423736013385728,http://twitter.com/4mysquad/statuses/641423736...,NaN,NaN,NaN

In [58]:
tweets_df.content[340:344].str.contains("\?")

340    False
341    False
342     True
343    False
Name: content, dtype: bool

In [50]:
tweets_df.content[340:343]

340    For those who don't let the truth get in the w...
341    A great thread to fully understand the situati...
342    We're baaaaack. What did we miss?  #FreeTennessee
Name: content, dtype: object

In [59]:
tweets_df = tweets_df[~tweets_df.content.str.contains("\?")]

In [60]:
tweets_df.shape

(4802, 21)

In [61]:
tweets_df

,external_author_id,author,content,region,language,publish_date,harvested_date,following,followers,updates,...,account_type,retweet,account_category,new_june_2018,alt_external_id,tweet_id,article_url,tco1_step1,tco2_step1,tco3_step1
0,906000000000000000,10_GOP,"""We have a sitting Democrat US Senator on tria...",Unknown,English,10/1/2017 19:58,10/1/2017 19:59,1052,9636,253,...,Right,0,RightTroll,0,905874659358453760,914580356430536707,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/914580356430...,NaN,NaN
1,906000000000000000,10_GOP,Marshawn Lynch arrives to game in anti-Trump s...,Unknown,English,10/1/2017 22:43,10/1/2017 22:43,1054,9637,254,...,Right,0,RightTroll,0,905874659358453760,914621840496189440,http://twitter.com/905874659358453760/statuses...,https://twitter.com/damienwoody/status/9145685...,NaN,NaN
2,906000000000000000,10_GOP,Daughter of fallen Navy Sailor delivers powerf...,Unknown,English,10/1/2017 22:50,10/1/2017 22:51,1054,9637,255,...,Right,1,RightTroll,0,905874659358453760,914623490375979008,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/913231923715...,NaN,NaN
3,906000000000000000,10_GOP,JUST IN: President Trump dedicates Presidents ...,Unknown,English,10/1/2017 23:52,10/1/2017 23:52,1062,9642,256,...,Right,0,RightTroll,0,905874659358453760,914639143690555392,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/914639143690...,NaN,NaN
4,906000000000000000,10_GOP,"19,000 RESPECTING our National Anthem! #StandF...",Unknown,English,10/1/2017 2:13,10/1/2017 2:13,1050,9645,246,...,Right,1,RightTroll,0,905874659358453760,914312219952861184,http://twitter.com/905874659358453760/statuses...,https://twitter.com/realDonaldTrump/status/914...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,3312143142,4MYSQUAD,Mom Says #Cop Slammed Son’s Face Into Newly La...,United States,English,9/9/2015 0:54,9/9/2015 0:54,1311,618,2078,...,Left,0,LeftTroll,0,3312143142,641414424163577856,http://twitter.com/4mysquad/statuses/641414424...,https://twitter.com/4mysquad/status/6414144241...,http://tmblr.co/ZSSdql1tkXKeM,NaN
9996,3312143142,4MYSQUAD,Rebecca Martin: Public Comment Against More #C...,United States,English,9/9/2015 1:18,9/9/2015 1:18,1311,618,2091,...,Left,0,LeftTroll,0,3312143142,641420337356210176,http://twitter.com/4mysquad/statuses/641420337...,https://www.youtube.com/watch?v=ffCiHzqMJIA,NaN,NaN
9997,3312143142,4MYSQUAD,'@ThisIsRobThomas If You believe - you act',United States,English,9/9/2015 1:29,9/9/2015 1:29,1311,620,2096,...,Left,0,LeftTroll,0,3312143142,641423168989630465,http://twitter.com/4mysquad/statuses/641423168...,NaN,NaN,NaN
9998,3312143142,4MYSQUAD,'@tyriquex when my girl refused to stop painti...,United States,English,9/9/2015 1:31,9/9/2015 1:31,1311,620,2097,...,Left,0,LeftTroll,0,3312143142,641423659505090560,http://twitter.com/4mysquad/statuses/641423659...,NaN,NaN,NaN
9999,3312143142,4MYSQUAD,'@deray New York State Of Mind',United States,English,9/9/2015 1:31,9/9/2015 1:31,1311,620,2098,...,Left,0,LeftTroll,0,3312143142,641423736013385728,http://twitter.com/4mysquad/statuses/641423736...,NaN,NaN,NaN

In [62]:
tweets_df.content.str.contains("\?")

0       False
1       False
2       False
3       False
4       False
        ...
9992    False
9996    False
9997    False
9998    False
9999    False
Name: content, Length: 4802, dtype: bool